Repository kimzoo2/tothebook, pull requests merged in 2023-06, with the labels that each got.

#2 Feat: 에러 핸들링에 에러 로그 추가
  src/main/java/com/std/tothebook/exception/GlobalExceptionHandler.java
Labels: 🍟 Chore

#3 Kimzoo 230619 log파일 생성추가
  src/main/resources/application.yml
Labels: 🍟 Chore

#4 Temp : PR 테스트
  src/main/java/com/std/tothebook/controller/ThymeleafController.java
Labels: 🤍 Temp

#1 Comment: PullRequest 테스트 용 주석 추가
  src/main/java/com/std/tothebook/api/service/UserService.java
Labels: 🍥 Comment

#5 Chore : ignore log 파일 제외 설정 추가
  .gitignore
Labels: 🍟 Chore

#6 Temp : 타임리프 예시 화면 및 기능 추가
  src/main/java/com/std/tothebook/controller/ThymeleafController.java
  src/main/resources/templates/viewtest/grammar/add.html
  src/main/resources/templates/viewtest/grammar/user.html
  src/main/resources/templates/viewtest/grammar/users.html
  src/main/resources/templates/viewtest/index.html
Labels: 🤍 Temp
