Repository kimzoo2/tothebook, pull requests merged in 2023-08, with the labels that each got.

#22 Feature/kimzoo 230802 std 11
  src/main/java/com/std/tothebook/api/controller/api/MyBookController.java
  src/main/java/com/std/tothebook/api/domain/dto/EditMyBookRequest.java
  src/main/java/com/std/tothebook/api/entity/MyBook.java
  src/main/java/com/std/tothebook/api/service/MyBookService.java
Labels: 🧸 BackEnd

#23 Feat: 이메일 발송 기능 추가
  build.gradle
  src/main/java/com/std/tothebook/api/controller/api/CertificationController.java
  src/main/java/com/std/tothebook/api/domain/dto/SendCertificationNumberRequest.java
  src/main/java/com/std/tothebook/api/service/CertificationService.java
  src/main/java/com/std/tothebook/api/service/EmailSendService.java
  src/main/resources/application.yml
  src/main/resources/templates/app/signUp/form.html
Labels: 🧸 BackEnd

#24 Feature/kimzoo 230803 std 15
  src/main/java/com/std/tothebook/api/controller/api/MyBookController.java
  src/main/java/com/std/tothebook/api/entity/Book.java
  src/main/java/com/std/tothebook/api/entity/Category.java
  src/main/java/com/std/tothebook/api/repository/BookRepository.java
  src/main/java/com/std/tothebook/api/repository/CategoryRepository.java
  src/main/java/com/std/tothebook/api/service/MyBookService.java
Labels: 😎 Refactor

#25 Feature/kimzoo 230803 std 10
  build.gradle
  src/main/java/com/std/tothebook/api/controller/api/MyBookController.java
  src/main/java/com/std/tothebook/api/domain/dto/AddMyBookRequest.java
  src/main/java/com/std/tothebook/api/service/MyBookService.java
Labels: 😎 Refactor

#26 Feature/seulhee 20230803 std 32
  src/main/java/com/std/tothebook/api/domain/dto/SendCertificationNumberRequest.java
  src/main/java/com/std/tothebook/api/entity/Certification.java
  src/main/java/com/std/tothebook/api/enums/CertificationType.java
  src/main/java/com/std/tothebook/api/service/CertificationService.java
Labels: 🧸 BackEnd

#27 Feat : 독서 기록(내 서재) 등록 기능 추가
  src/main/java/com/std/tothebook/api/controller/api/MyBookController.java
  src/main/java/com/std/tothebook/api/entity/MyBook.java
  src/main/java/com/std/tothebook/api/service/MyBookService.java
Labels: 🧸 BackEnd

#28 Feature/seulhee 20230807 std 32
  src/main/java/com/std/tothebook/api/controller/api/CertificationController.java
  src/main/java/com/std/tothebook/api/domain/dto/ValidateCertificationNumberRequest.java
  src/main/java/com/std/tothebook/api/entity/Certification.java
  src/main/java/com/std/tothebook/api/repository/CertificationRepository.java
  src/main/java/com/std/tothebook/api/service/CertificationService.java
  src/main/java/com/std/tothebook/exception/CertificationException.java
  src/main/java/com/std/tothebook/exception/enums/ErrorCode.java
  src/main/resources/application.yml
Labels: 🧸 BackEnd

#29 Feat: 닉네임 중복 체크 기능 추가
  src/main/java/com/std/tothebook/api/controller/api/UserController.java
  src/main/java/com/std/tothebook/api/repository/UserRepository.java
  src/main/java/com/std/tothebook/api/service/UserService.java
Labels: 🧸 BackEnd

#31 Fix: 인증번호 발송 전 이메일 규칙 체크 추가
  src/main/java/com/std/tothebook/api/service/CertificationService.java
Labels: 🐛 Bug
