Repository kimzoo2/tothebook, pull requests merged in 2023-07, with the labels that each got.

#9 fix: 어플리케이션 실행 시 Security exclude 설정 제거
  src/main/java/com/std/tothebook/TothebookApplication.java
Labels: 🍟 Chore

#10 Design : 공통 헤더, 네비게이션 바 변경
  src/main/resources/templates/common/header.html
  src/main/resources/templates/common/navigatorBar.html
Labels: 🌷 UI

#12 Feat : 독서기록 리스트 조회, 독서기록 상세 조회
  src/main/java/com/std/tothebook/api/controller/api/MyBookController.java
  src/main/java/com/std/tothebook/api/domain/dto/FindMyBookResponse.java
  src/main/java/com/std/tothebook/api/domain/dto/FindMyBooksResponse.java
  src/main/java/com/std/tothebook/api/entity/Book.java
  src/main/java/com/std/tothebook/api/entity/Category.java
  src/main/java/com/std/tothebook/api/entity/MyBook.java
  src/main/java/com/std/tothebook/api/enums/MyBookStatus.java
  src/main/java/com/std/tothebook/api/repository/MyBookCustomRepository.java
  src/main/java/com/std/tothebook/api/repository/impl/MyBookCustomRepositoryImpl.java
  src/main/java/com/std/tothebook/api/service/MyBookService.java
  src/main/resources/templates/app/mybook/myBooks.html
Labels: 🧸 BackEnd

#13 Feat: Refresh Token 기능 추가
  src/main/java/com/std/tothebook/api/controller/api/TokenController.java
  src/main/java/com/std/tothebook/api/entity/RefreshToken.java
  src/main/java/com/std/tothebook/api/repository/RefreshTokenRepository.java
  src/main/java/com/std/tothebook/api/service/JwtTokenService.java
  src/main/java/com/std/tothebook/api/service/TokenService.java
  src/main/java/com/std/tothebook/config/JwtTokenProvider.java
  src/main/java/com/std/tothebook/security/filter/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: 🧸 BackEnd

#14 Refactor : 독서기록 조회 기능 변경 (PR 반영 등)
  src/main/java/com/std/tothebook/api/controller/api/MyBookController.java
  src/main/java/com/std/tothebook/api/domain/dto/FindMyBookResponse.java
  src/main/java/com/std/tothebook/api/domain/dto/FindMyBooksResponse.java
  src/main/java/com/std/tothebook/api/entity/Book.java
  src/main/java/com/std/tothebook/api/entity/MyBook.java
  src/main/java/com/std/tothebook/api/enums/MyBookStatus.java
  src/main/java/com/std/tothebook/api/repository/MyBookCustomRepository.java
  src/main/java/com/std/tothebook/api/repository/impl/MyBookCustomRepositoryImpl.java
  src/main/java/com/std/tothebook/api/service/MyBookService.java
Labels: 😎 Refactor

#16 Design : 화면 공통부 타임리프 선언 수정
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/common/navigatorBar.html
Labels: 🌷 UI

#18 Refactor: jQuery, axios 추가 코드 fragment 분리
  src/main/resources/templates/app/signIn/form.html
  src/main/resources/templates/common/script.html
  src/main/resources/templates/index.html
Labels: ✨ FrontEnd, 😎 Refactor

#19 Refactor : 엔티티 연관관계 변경, 필드 변수 타입 변경 및 Repository 인터페이스 추가
  src/main/java/com/std/tothebook/api/entity/Book.java
  src/main/java/com/std/tothebook/api/entity/MyBook.java
  src/main/java/com/std/tothebook/api/repository/MyBookRepository.java
  src/main/java/com/std/tothebook/api/service/MyBookService.java
Labels: 😎 Refactor

#21 Feat : 독서 기록(내 서재) 등록 기능 추가
  src/main/java/com/std/tothebook/api/controller/api/MyBookController.java
  src/main/java/com/std/tothebook/api/domain/dto/AddMyBookRequest.java
  src/main/java/com/std/tothebook/api/entity/Book.java
  src/main/java/com/std/tothebook/api/entity/MyBook.java
  src/main/java/com/std/tothebook/api/service/MyBookService.java
Labels: 🧸 BackEnd, 😎 Refactor
