Repository kimzoo2/tothebook, pull requests merged in 2024-08, with the labels that each got.

#37 Chore: local h2 DB로 변경
  build.gradle
  src/main/java/com/std/tothebook/security/SecurityConfig.java
  src/main/resources/application-local.yml
Labels: 🍟 Chore

#36 Refactor: 나의 독서 기록 테스트 코드 추가 및 ArgumentResolver 활용하여 로그인 객체 조회
  src/main/java/com/std/tothebook/controller/api/MyBookController.java
  src/main/java/com/std/tothebook/dto/FindMyBookDetailResponse.java
  src/main/java/com/std/tothebook/dto/FindMyBookResponse.java
  src/main/java/com/std/tothebook/dto/FindMyBooksResponse.java
  src/main/java/com/std/tothebook/entity/Category.java
  src/main/java/com/std/tothebook/entity/Certification.java
  src/main/java/com/std/tothebook/entity/MyBook.java
  src/main/java/com/std/tothebook/entity/User.java
  src/main/java/com/std/tothebook/repository/MyBookCustomRepository.java
  src/main/java/com/std/tothebook/repository/MyBookRepository.java
  src/main/java/com/std/tothebook/repository/impl/MyBookCustomRepositoryImpl.java
  src/main/java/com/std/tothebook/service/MyBookService.java
  src/test/java/com/std/tothebook/helper/IntegrationTestHelper.java
  src/test/java/com/std/tothebook/helper/TestQueryDslConfig.java
  src/test/java/com/std/tothebook/repository/MyBookRepositoryTest.java
  src/test/java/com/std/tothebook/service/MyBookServiceTest.java
  src/test/resources/application.yml
Labels: 😎 Refactor

#38 Refactor: MyBookController 코멘트 변경 및 리팩토링
  src/main/java/com/std/tothebook/controller/api/MyBookController.java
Labels: 😎 Refactor

#39 Feat: 커스텀 어노테이션 기반 로그인 유저 정보 가져오기 기능 추가
  src/main/java/com/std/tothebook/annotation/User.java
  src/main/java/com/std/tothebook/common/WebConfig.java
  src/main/java/com/std/tothebook/common/resolvers/LoginUserArgumentResolver.java
  src/main/java/com/std/tothebook/config/JwtTokenProvider.java
  src/main/java/com/std/tothebook/controller/api/MyBookController.java
  src/main/java/com/std/tothebook/dto/LoginUserResponse.java
  src/main/java/com/std/tothebook/exception/enums/ErrorCode.java
  src/main/java/com/std/tothebook/security/CustomUserDetailsService.java
  src/main/java/com/std/tothebook/security/LoginUser.java
  src/main/java/com/std/tothebook/service/SignInService.java
  src/main/java/com/std/tothebook/service/UserService.java
  src/test/java/com/std/tothebook/common/resolvers/LoginUserArgumentResolverTest.java
Labels: 🧸 BackEnd
